### ISSUE TITLE
mithril-client fails to extract archive

### ISSUE THREAD

**Issue by v0d1ch** [input-output-hk/mithril#1352]
## Context & versions
When running mithril-client on aws machine it fails to extract the downloaded archive:

## Steps to reproduce

```
mithril-client --run-mode mainnet snapshot download f7f4b404c879c91386f9eb7d24856e838e535702b8b41ad8671b1fca22d92ae8
1/7 - Checking local disk info… 
2/7 - Fetching the certificate's information… 
3/7 - Verifying the certificate chain…
4/7 - Downloading the snapshot…
5/7 - Unpacking the snapshot…

Error: "An error occured: Could not unpack './snapshot-f7f4b404c879c91386f9eb7d24856e838e535702b8b41ad8671b1fca22d92ae8.tar.gz' in directory './db'. Error: « failed to iterate over archive »."


$ cat /proc/version
Linux version 5.15.0-1048-aws (buildd@lcy02-amd64-055) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #53~20.04.1-Ubuntu SMP Wed Oct 4 16:44:20 UTC 2023

```

## Actual behavior
Error occurred `Could not unpack ... failed to iterate over archive`

## Expected behavior
We expect the command to extract the snapshot contents into a db folder.

**Comment by jpraynaud** [comment]
It looks like your issue is due to the version of the `mithril-client` your are running. 
You should run the version `0.4+` to avoid this issue.

Can you check the version you are running with:
```bash
$ ./mithril-client --version
mithril-client 0.4.12+e5ae362
```
You can download the correct version from the latest distribution:
- [release notes](https://github.com/input-output-hk/mithril/releases/tag/2342.0)
- [compiled binaries for Linux](https://github.com/input-output-hk/mithril/releases/download/2342.0/mithril-2342.0-linux-x64.tar.gz)

**Comment by v0d1ch** [comment]
You are righ, I was running an older version. Thanks!
