### ISSUE TITLE
Mithril Signer Local Error Policy : Error 182 - MuxError

### ISSUE THREAD

**Issue by Kirael12** [input-output-hk/mithril#1632]
## Context & versions
cardano node version 8.9.1.
mithril-signer v2412.0.
Fresh mithril-signer setup on BP. Squid on Relay.
Pool is correctly registered on Mithril Explorer.

## Actual behavior
Every 60 seconds, only when mithril-signer is running, this error appears in cardano-node process syslog : 

cardano.node.LocalErrorPolicy:Error:182 IP LocalAddress "<PATH TO SOCKET>/socket@58" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 58> closed when reading data, waiting on next header True")

**Comment by jpraynaud** [comment]
@falcucci is this something that could be related to the way pallas is communicating with the Cardano node? 
(The Mithril signer is retrieving the epoch from the node at this pace of once every mninute)

**Comment by jpraynaud** [comment]
@scarmuega FYI, this is the issue we talekd about during Office Hours

**Comment by ch1bo** [comment]
Could be because a non-graceful shutdown of the local state query. We should double-check whether the mithril-signer is sending a `MsgRelease` and `MsgDone` after the query.

**Comment by jpraynaud** [comment]
Also seen on the `devnet`:
```bash
[jp:cardano.node.LocalErrorPolicy:Error:64] [2024-04-16 13:22:14.42 UTC] IP LocalAddress "node-pool2/ipc/node.sock@11042" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 34> closed when reading data, waiting on next header True")
[jp:cardano.node.LocalErrorPolicy:Error:64] [2024-04-16 13:22:14.42 UTC] IP LocalAddress "node-pool2/ipc/node.sock@11043" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 35> closed when reading data, waiting on next header True")
[jp:cardano.node.LocalErrorPolicy:Error:64] [2024-04-16 13:22:14.46 UTC] IP LocalAddress "node-pool2/ipc/node.sock@11044" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 36> closed when reading data, waiting on next header True")
```

**Comment by perseus-algol** [comment]
I can try to investigate it

**Comment by perseus-algol** [comment]
## Steps to reproduce

To reproduce this issue it is enough just to run the devnet and watch logs:

```bash
# Terminal 1
cd mithril-test-lab/mithril-devnet
SKIP_CARDANO_BIN_DOWNLOAD=true \
FORCE_DELETE_ARTIFACTS_DIR=true \
NUM_BFT_NODES=1 NUM_POOL_NODES=2 ./devnet-run.sh

# Terminal 2
cd mithril-test-lab/mithril-devnet/artifacts && tail -n 62 -f ./node-pool1/node.log

# Terminal 3
docker logs -f artifacts-mithril-signer-node-pool1-1
```

Then after some time you will see in Terminal 2 an error 
```
[andrew-d:cardano.node.LocalErrorPolicy:Error:62] [2024-04-18 13:51:30.14 UTC] IP LocalAddress "node-pool1/ipc/node.sock@3" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 28> closed when reading data, waiting on next header True")
```

and in Terminal 3 `could not retrieve epoch settings at epoch Epoch(1)` with nested error: `Epoch service was not initialized, the function inform_epoch must be called first`. 

## Causes

Signing node called `/epoch-settings` HTTP-endpoint of an aggregator. And the aggregator responds with an error `Epoch service was not initialized, the function inform_epoch must be called first`, which means:

```rust
    /// Raised when service has not collected data at least once.
    #[error("Epoch service was not initialized, the function `inform_epoch` must be called first")]
    NotYetInitialized,
```
So it is obviously that `epoch_service` wasn't initialized by calling `inform_epoch` first. 

## Finding the root cause

I'm not sure at the moment where `epoch_service` should be initialized by calling `inform_epoch`.One thing I notices is that there is `self.runner.inform_new_epoch(new_time_point.epoch).await?;` call in `mithril-aggregator/src/runtime/state_machine.rs`. And this seemed the only place where `inform_epoch` is called.

**Comment by jpraynaud** [comment]
> ## Steps to reproduce
> To reproduce this issue it is enough just to run the devnet and watch logs:

You are right, running the `devnet` is not enough. In order to reproduce the problem, you can run the end to end test:
```bash
cargo build --release -p mithril-aggregator -p mithril-signer -p mithril-client-cli && cargo run -p mithril-end-to-end -- -vvvv --bin-directory target/release/ --work-directory=./artifacts --devnet-scripts-directory=./mithril-test-lab/mithril-devnet
```
or this one to keep the network alive:
```bash
cargo build --release -p mithril-aggregator -p mithril-signer -p mithril-client-cli && cargo run -p mithril-end-to-end -- -vvvv --bin-directory target/release/ --work-directory=./artifacts --devnet-scripts-directory=./mithril-test-lab/mithril-devnet --run-only
```

The problem is happening on the signer node so you should probably investigate what's happening between the Mithril signer and the Cardano node. The signer is asking the node the current epoch at regular interval (usually 2 min in production) and this is done by the [`ChainObserver`](https://github.com/input-output-hk/mithril/blob/0f094fb8821e9ce5344aa1871f78d542c0428a55/mithril-common/src/chain_observer/pallas_observer.rs#L35-L36) which takes care of handling the n2c communcations.

**Comment by perseus-algol** [comment]
@jpraynaud , thank you for pointing to e2e tests and to the right direction. I left a comment in #1644. Not 100% sure that this is correct solution, it seems works and error message is not appearing anymore.

**Comment by jpraynaud** [comment]
After investigation, it appears that this is a normal behavior of the Cardano node and that it should probably not be flagged as an error (see https://github.com/input-output-hk/mithril/pull/1644#issuecomment-2161029856 for more details).
