### ISSUE TITLE
PoC implementation with `avro`

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#678]
## PoC Scenario
Add/Remove/Update a field `message_type` on the single signature that is sent from the Signer to the Aggregator:
In that case, the Aggregator would receive 2 different kinds of message from the updated/non-updated signers.
We want to avoid breaking changes that would prevent the network from producing certificates for one epoch.

## To do

- [x] Assess technical constraints of the [`avro`](https://avro.apache.org/) implementation.
- [x] Develop prototypical implementations of `avro` implementations 

:warning:  the minimum requirement for the implementation is that the end to end test is working

## Parent issue
#673

**Comment by Alenar** [comment]
A proof of concept have been done on the following branch: [djo/678/avro_poc](https://github.com/input-output-hk/mithril/tree/djo/678/avro_poc).

### Technical aspects

There's an official rust implementation, still in beta, that can be used to read/write data using a Avro schema : [apache-avro](https://crates.io/crates/apache-avro).
Note: this implementation doesn't seems to handle Avro protocols _(maybe I missed something ?)_.

Contrary to Protobuf you don't needs to compile Avro schemas. You use schemas directly when using Avro Writer (and optionally Avro Reader) to write/read data.

There's an non-official crate that generate rust types from Avro schemas: [rsgen-avro](https://crates.io/crates/rsgen-avro).

The Avro type system is more limited than the rust one (no surprise here), but this leads to a few caveats. The most annoying one that I saw is that there's no unsigned number types and since the `long` Avro type is mapped to `i64` this mean that we can't use a `u64` in our mappings (we can at most use `u32` since it's enclosed in `i64`).

### Schema upgrades aspects:

- There's nothing automatic embedded in Avro.
- A `SchemaCompatibility` tool allow to check that a read and a write schemas are compatible with each others but it must be run manually in the code (likely in a unit test).
  - This means that we would have to keep older schemas.
  - When making updates it could be used to ensure that the older write schema is compatible with the updated read schema. 
- If the schema change is limited to adding new fields you can add a default value that will only be used when reading older data (writing data would still needs the new fields).

There's nothing more than that to handle gracefully schema changes, changing a field type or part of the schema structure would still have to be handled manually.

### Conclusion

I'm skeptical  to the interest of using Avro for our message in our systems, in one hand it would allow to:
- have schema defined messages, something interesting if we want nodes coded with heterogeneous programing languages but ... that not the case right now nor it will be in the forseeable future.
- have some limited tools to check upgraded schema compatibility against older schema.

On other hands it would:
- not bring much over `serde` for the most common schema change: adding new fields (the [serde default attribute](https://serde.rs/attr-default.html) do the same thing than Avro default value).
- not bring much help for structure & types schema changes: as today we would have to handle them manually or avoid them as long as possible.
- add a complexity layer on top of our network stack to serialize/deserialize Avro encoded messages.
- limit the kind of data that we can exchange by restricting them to the types that Avro knows.
