### ISSUE TITLE
Mithril client fails to restore snapshot.

### ISSUE THREAD

**Issue by ffakenz** [input-output-hk/mithril#791]
## Context & versions
Running an ubuntu node with the following specs
```
Operating System: Ubuntu 20.04.5 LTS
Kernel: Linux 5.15.0-1017-aws
Architecture: x86-64
```
and using the mithril-client docker image with tag `unstable`.

NOTE: using the `latest` tag produces the following error
```
app/bin/mithril-client: error while loading shared libraries: libsqlite3.so.0: cannot open shared object file: No such file or directory
```
but this is a known bug in the docker image reported 2 weeks ago on discord https://discord.com/channels/826816523368005654/1014019542504185876/1078322175674695810 

## Steps to reproduce

1/ pull docker image for mithril-client

```sh
docker pull ghcr.io/input-output-hk/mithril-client:unstable
```

2/ setup helpers

```sh
GENESIS_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/release-preprod/genesis.vkey) 

SNAPSHOT=$(curl -s https://aggregator.release-preprod.api.mithril.network/aggregator/snapshots | jq -r '.[0].digest')

mithril_client () {
  docker run --rm -ti -e GENESIS_VERIFICATION_KEY=$GENESIS_VERIFICATION_KEY -e NETWORK=release-preprod -v $(pwd):/data -e AGGREGATOR_ENDPOINT=https://aggregator.release-preprod.api.mithril.network/aggregator -w /data -u $(id -u) ghcr.io/input-output-hk/mithril-client:unstable $@
}
```

3/ run the above helper function for the mithril client

```sh
mithril_client restore $SNAPSHOT
```

## Actual behavior
Getting the following error
```
Unpacking snapshot...
Error: "An error occured: \"Failure when creating cache directory `/home/appuser/.cache/mithril`: Permission denied (os error 13)\""
```

## Expected behavior
I can restore my cardano-node from a valid downloaded snapshot in `release-preprod` network.

**Comment by jpraynaud** [comment]
Hi @ffakenz, we have fixed the problem that you had when using the Docker image of the Mithril client.

Please find an updated process to restore a snapshot from the `release-preprod` network (this will run an `unstable` image as the fix is not part of a release yet):
- Setup env vars:
```
export MITHRIL_IMAGE_ID=unstable
export NETWORK=preprod
export AGGREGATOR_ENDPOINT=https://aggregator.release-preprod.api.mithril.network/aggregator
export GENESIS_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/release-preprod/genesis.vkey)
export SNAPSHOT_DIGEST=$(curl -s $AGGREGATOR_ENDPOINT/snapshots | jq -r '.[0].digest')
```
- Updated `mithril_client`shell function:
```
mithril_client () {
  docker run --rm -e NETWORK=$NETWORK -e GENESIS_VERIFICATION_KEY=$GENESIS_VERIFICATION_KEY -e AGGREGATOR_ENDPOINT=$AGGREGATOR_ENDPOINT --name='mithril-client' -v $(pwd):/app/data -u $(id -u) ghcr.io/input-output-hk/mithril-client:$MITHRIL_IMAGE_ID $@
}
```
- Pull Docker image:
```
docker pull ghcr.io/input-output-hk/mithril-client:$MITHRIL_IMAGE_ID
```
- Download and restore the snapshot:
```
# Download latest snapshot
mithril_client download $SNAPSHOT_DIGEST

# Restore latest snapshot
mithril_client restore $SNAPSHOT_DIGEST
```
We have also added sections on how to use the Docker image of the Client in our doc:
- [Mithril Client Node](https://mithril.network/doc/next/manual/developer-docs/nodes/mithril-client#run-docker-container) developers doc
- [Bootstrap a Cardano Node](https://mithril.network/doc/next/manual/getting-started/bootstrap-cardano-node#run-docker-container) user guide

Let us know if everything works as expected now :slightly_smiling_face:

**Comment by ffakenz** [comment]
Worked like a charm!

Thank you for the help and support! 🙏
